spring:
  data:
    mongodb:
      uri: mongodb+srv://sumanth:dbPwd@cluster0.jghdd2b.mongodb.net/?retryWrites=true&w=majority
      database: consentEventDB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher




